export const SET_ITEMS = 'SET_ITEMS';
export const GET_FEATURED_ITEMS = 'GET_FEATURED_ITEMS';
export const ACTION_ITEM_SUCCESS = 'ACTION_ITEM_SUCCESS';
export const ACTION_ITEM_FAILED = 'ACTION_ITEM_FAILED';

export const AUTH_START = 'AUTH_START'; 
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';